export const jokes = [
  "Your Momma is so ugly she has to sneak up on the mirror.",
  "Yo Momma is so ugly, when she went into a haunted house she came out with a job application.",
  "Yo Momma is so ugly, the government moved Halloween to her birthday!",
  "Your Momma is so ugly she made an onion cry.",
  "Yo Momma is so ugly when she took a bath the water jumped out.",
  "Yo Momma is so fat, I took a picture of her last Christmas and it's still printing.",
  "Yo Momma is so fat, that when she went to the zoo, the hippos got jealous. ",
  "Yo Momma is so fat, she walked past the TV and I missed 3 episodes of Breaking Bad.",
  `"Yo Momma is so fat, when she steps out in a yellow raincoat, people yell, "TAXI!"`,
  "Yo Momma is so fat, I tried driving around her and I ran out of petrol.",
  "Yo Momma is so fat, not even Dora can explore her.",
  "Yo Momma is so old, when we watched Jurrasic Park she started having flashbacks.",
  "Yo Momma is so old, her first car was a Model T-Rex.",
  "Yo Momma is so old, that when she was in school there was no history class.",
  "Yo Momma is so old, that her memory is in black and white.",
  "Yo Momma is so old, she knew Burger King when he was a prince.",
  "Yo Momma is so fat her bellybutton gets home 15 minutes before she does.",
  "Yo Momma is so fat she doesn't need the internet, because she's already world wide.",
  "Yo Momma is so fat, when she sat on an iPod, she made the iPad!",
  "Yo Momma is so stupid she brought a spoon to the Superbowl.",
  "Yo Momma is so fat she needs cheat codes for Wii Fit.",
  "Yo Momma is so ugly, when she goes into a strip club, they pay her to keep her clothes on.",
  "Yo Momma is so fat, she got baptized at Sea World.",
  "Yo Momma is so fat, her baby pictures were taken by satellite.",
  "Yo Momma is so fat, when she sat on the back of the bus it did a wheelie.",
  "Yo Momma is so stupid, she got hit by a parked car.",
  `Yo Momma is so fat, when she stepped on a scale it said, "One person at a time please."`,
  `Yo Momma is so fat when she went to KFC the cashier asked, "What size bucket?" and yo momma said, "The one on the roof."`,
  "Yo Momma is so fat, when she skips a meal, the stock market drops.",
  `Yo Momma is so stupid, she stared at a cup of orange juice for 12 hours because it said "concentrate.`,
  "Yo Momma is so stupid, she thought a quarterback was a refund.",
  `Yo Momma is so stupid, when they said, "Order in the court," she asked for fries and a shake.`,
  "Yo Momma is so stupid, when I told her that she lost her mind, she went looking for it",
  "Yo Momma is so stupid, she went to the dentist to get Bluetooth.",
  `Yo Momma is so stupid, when I said, "Drinks on the house," she got a ladder.`,
  "Yo Momma is so stupid, she put airbags on her computer in case it crashed.",
  "Yo Momma is so lazy, she stuck her nose out the window and let the wind blow it.",
  "Yo Momma is so miserable, blues singers come to visit her when they've got writer's block.",
  "Yo Momma is so ugly, her birth certificate is an apology letter.",
  "Yo Momma is so stupid, she got locked in a mattress store and slept on the floor.",
  "Yo Momma is so old, she was a waitress at the Last Supper.",
  "Yo Momma is so fat, she makes Godzilla look like an action figure.",
  "Yo Momma is so dumb, she put a watch in a piggybank and said she was saving time.",
  `Yo Momma is so mean, they don\'t give her happy meals at McDonalds.`,
  "Yo Momma is so lazy, she has a stay-at-home job and is still late to work.",
  "Yo Momma is so fat, she can't even jump to a conclusion.",
  "Yo Momma is so dumb, she called me to ask for my phone number.",
  "Yo Momma is so old, when someone told her to act her age, she died.",
  "Yo Momma is so dumb, she put sugar on the bed because she wanted sweet dreams.",
  "Yo Momma is so poor she can't even pay attention.",
  "Yo Momma is so stupid, she studied for a Covid test.",
];
